### ISSUE TITLE
Tooling for VSCode

### ISSUE THREAD

**Issue by galvesribeiro** [ghi-electronics/Tools#3]
Hello folks!

I noticed the extensions are only for Visual Studio on Windows.

I was wondering if the tooling embedded on the VSIX to attach debugger etc could be OSSed here so we could add support to VSCode and cross-platform development like on OSX and Linux for tinyCLR tools.

Thank you! Great work!

**Comment by galvesribeiro** [comment]
BTW, I was looking at `GHIElectronics.TinyCLR.Debugger.dll` and the configurator tool, I don't see any Windows-specific dependency. 

You don't need to OSS it, I would just build the extension around those dlls. 

It would be good if it was available as a nuget package.

Also, do you guys think it would be something we could add a repo on this organization and I could add PRs to it? Or should I host it somewhere else?

**Comment by Arke64** [comment]
Thanks for the interest!

VS Code is definitely something we're interested in, but don't have anything quite at this moment for it.

You're right that the debugger library is pretty generic and not VS or Windows specific. It is generally designed to be consumed by various tools to automate device interaction (including deployment and debugging). While it's not quite ready for official release in that capacity, you're welcome to explore and use it, just keep in mind it may change in future releases until we stabilize. Releasing it as a nuget package is on our list, but we don't have any date to commit to just yet.

For now, we'd host any work you do elsewhere. We can always re-evaluate down the road.

**Comment by galvesribeiro** [comment]
OK. Thank you @Arke64! 

Will follow that path and let you know about my findings.

Thank you!
